baseURL = "https://asynkron.se/"
languageCode = "en-us"
title = "Asynkron AB"
theme = "blank"
# relativeURLs = "true"
# uglyURLs = "true"
# [params]
#   ugly = ".html"
#   uglyhome = "/index.html"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula" #https://xyproto.github.io/splash/docs/all.html
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]