baseURL = "https://asynkron.se/"
languageCode = "en-us"
title = "Asynkron AB"
theme = "blank"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "xcode"
    tabWidth = 4