baseURL = "https://asynkron.se/"
languageCode = "en-us"
title = "Asynkron AB"
theme = "blank"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 4